# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-04 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='abc'),
            preserve_default=False,
        ),
    ]
