# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-05 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampsFacl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facl', models.CharField(max_length=20)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.Camps')),
            ],
        ),
        migrations.CreateModel(
            name='CampsItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=20)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ngo.Camps')),
            ],
        ),
    ]
